artifactory:
  artifactory:
    service:
      type: NodePort
  nginx:
    enabled: false
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - "nexus.local.thongdanghoang.id.vn"
    tls: []
  postgresql:
    postgresqlPassword=April03,2001: