apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven-repo-cache
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce # ReadWriteMany fallback
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path