apiVersion: v1
kind: Service
metadata:
  name: sonarqube-postgresql
  namespace: thongdhse160015-dev
spec:
  type: ExternalName
  externalName: postgresql.thongdhse160015-dev.svc.cluster.local
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432