community:
  enabled: true

ingress:
  enabled: true
  hosts:
    - name: sonarqube.local
      path: /
      pathType: Prefix
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "local-ca-issuer"
  tls:
    - secretName: sonarqube-tls-secret
      hosts:
        - sonarqube.local

persistence:
  enabled: true

sonarProperties:
  sonar.core.serverBaseURL: "https://sonarqube.local"
  sonar.web.javaAdditionalOpts: "-Dsonar.forceAuthentication=true"
