community:
  enabled: true

ingress:
  enabled: true
  hosts:
    - name: sonarqube.local
      path: /
      pathType: Prefix
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  tls: []

persistence:
  enabled: true
  size: 10Gi

sonarProperties:
  sonar.core.serverBaseURL: "http://sonarqube.local"

monitoringPasscodeSecretName: "sonarqube-monitoring-passcode"
monitoringPasscodeSecretKey: "passcode"
