expose:
  type: ingress
  tls:
    certSource: secret
    secret:
      secretName: "haber-tls-local"
  ingress:
    hosts:
      core: harbor.local
    className: "nginx"
    annotations:
      ingress.kubernetes.io/proxy-body-size: "0"
      ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      cert-manager.io/cluster-issuer: "local-ca-issuer"

externalURL: https://harbor.local
ipFamily:
  ipv6:
    enabled: false

core:
  hostAliases:
    - ip: "192.168.139.2"
      hostnames:
        - "keycloak.local"
